### ISSUE TITLE
Tests failing for lottoritter-core 

### ISSUE THREAD

**Issue by ambarnigade** [Lottoritter/lottoritter-platform#1]
trying to do maven install , build tests are failing
attaching failing tests surefire report,  unable to resolve the erros, hence raising the issue 
[surefire-reports.zip](https://github.com/Lottoritter/lottoritter-platform/files/2607942/surefire-reports.zip)

**Comment by ulrichcech** [comment]
Thanks for submitting this issue. I resolved the testcases, now all tests should work fine again.

**Comment by crzo** [comment]
All tests are running, so i close this issue. Thank you for submitting this issue
